name: Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install sshpass
        run: sudo apt-get install sshpass

      - name: Deploy my App on Server
        run: |
          sshpass -p ${{ secrets.SSH_PASSPHRASE }} ssh -o StrictHostKeyChecking=no root@${{ secrets.IP_VPS }} << 'EOF'
            cd /path/to/your/directory
            mkdir -p qweqweqweqweqweqweqw
            # Add your deployment commands here
          EOF
