name: Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Install sshpass
        run: sudo apt-get install -y sshpass

      - name: Connect to server and run commands
        env:
          SERVER_USER: root
          SERVER_IP: ${{ secrets.IP_VPS }}
          SERVER_PASSWORD: ${{ secrets.VDS_PASSWORD }}
        run: |
          sshpass -p "$SERVER_PASSWORD" ssh -o StrictHostKeyChecking=no $SERVER_USER@$SERVER_IP << 'EOF'
          echo "Connected to the server using password!"
          cd /
          mkdir qweqweqweqweqweqweqw
          EOF

      - name: Print deploy message
        run: echo "Deploy job running!"
