name: Deploy to Server NetIT

on:
  push:
    branches:
      - main

jobs:
  build:
    steps:
      - name: Print message
        run: echo "Hello, this is a simple text output!"

  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Print deploy message
        run: echo "Deploy job running!"
