name: Connect to Ubuntu Server

on:
  push:
    branches:
      - main

jobs:
  ssh:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Connect to Ubuntu server via SSH
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.IP_VPS }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            echo "Connected successfully!"
            cd /
            mkdir qweqweqweqweqweqweqwe
