name: Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up SSH key
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy my App on Server
        run: |
          ssh -o StrictHostKeyChecking=no root@${{ secrets.IP_VPS }} << 'EOF'
            cd /
            mkdir -p qweqweqweqweqweqweqw
            # Добавьте свои команды деплоя здесь
          EOF
